---
# tasks file for ansible
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the ansible in Redhat derivates
  yum:
    name: "{{ ansible_pkgs }}"
    enablerepo: "'epel"
    state: present
  when: ansible_os_family == 'RedHat'

- include_tasks: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install the packages in Debian derivates
  apt:
    name: "{{ ansible_pkgs }}"
    state: present
    update_cache: true
    cache_valid_time: 600
  when:
    - ansible_os_family == 'Debian' 
